#!/bin/bash

script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# If PYTHONPATH is not set, set it to script_dir
# If it is set, prepend script_dir to it with colon seperator so that
# script_dir is prioritized

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH="$script_dir"
else
    export PYTHONPATH="$script_dir:$PYTHONPATH"
fi

# windows only
source "$script_dir/.venv/Scripts/activate"

"$@"