from __future__ import annotations
from typing import Protocol, Tuple, runtime_checkable


Envelope = Tuple[float, ...]


class ADSR(Protocol):
    def generate(self, num_samples: int) -> Envelope: ...
    def reset(self) -> None: ...
    def note_on(self) -> None: ...
    def note_off(self) -> None: ...